version: "3.7"

services:
  expo: # Name of the frontend service
      container_name: bsion-truyen-fe
      image: registry.gitlab.com/bsio1/truyen-fe:release
      deploy:
          resources:
            limits:
              cpus: '0.50'
            reservations:
              cpus: '0.25'
      ports:
         - 19000:19000 # Specify port-forwarding
         - 19001:19001
         - 19002:19002
         - 8880:8880
      environment:
         - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
         - REACT_NATIVE_PACKAGER_HOSTNAME=app-beta.bs.io.vn
         - PUBLIC_API_URL=https://truyen.bs.io.vn/api
         - EXPO_TOKEN=Tg1MuMCvzfD2HtNpRQTB7ne05JsXHoMFdOjrD7AE
  bsion-truyen-web-fe:
    container_name: bsion-truyen-web-fe
    image: registry.gitlab.com/bsio1/bson-spa-fe:release
    deploy:
      resources:
        limits:
          cpus: '0.50'
        reservations:
          cpus: '0.25'
    environment:
      - NEXT_PUBLIC_API_URL=https://truyen.bs.io.vn/api
    ports:
      - "3000:3000"
    networks:
      - my_network
networks:
  my_network:
    name: my-shared-db-network
    driver: bridge
    external: true
  default: # this network (app1)
        driver: bridge
