"use client";
import './globals.css';
import { usePathname } from 'next/navigation';
import Head from 'next/head';
import Navbar from './components/nav/NavBar';
import { apiClientUser } from './api/api-client';
import { useEffect } from 'react';

export default function RootLayout({ children }) {
  useEffect(() => {
    const fetchData = async () => {
      await apiClientUser();
    };
    fetchData();
  }, []);
  
  const pathname = usePathname();
  const noNavbarPaths = ['/login', '/register'];
  const showNavbar = !noNavbarPaths.includes(pathname) && !pathname.startsWith('/admin/dashboard');

  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>BSON Spa</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet" />
      </Head>
      <body className="font-roboto-condensed">
        {showNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
