export const EMAIL_ALREADY_IN_USE = "Email đã có người sử dụng";
export const NETWORK_ERROR = 'Tài khoản và mật khẩu sai';
export const INVALID_EMAIL_ERROR = "Email không hợp lệ"
export const SERVER_ERROR = 'SERVER_ERROR';
export const REGISTERED_SUCCES = 'Đăng ký thành công';
export const PASS_NOTMATCH = "Mật khẩu không khớp";
export const PASSWORD_CASE_ERROR = "Mật khẩu phải có in hoa";
export const PASSWORD_LENGTH_ERROR = "Mật khẩu phải trên 6 ký tự";
export const PASSWORD_SPECIAL_CHAR_ERROR = "Mật khẩu phải có ký tự đặc biệt";
export const PASS_NOMATCH = "Mật khẩu không khớp";
export const EMPTY_FIELD_ERROR = "Trường không được bỏ trống";
export const NEWPASSWORD_NOT_SAME_OLD = "Mật khẩu mới không được giống mật khẩu cũ.";
export const EMAIL_INUSE = "Email đã được sử dụng";
export const USER_INUSE = "Tên đăng nhập đã có người sử dụng";
export const EDIT_SUCCES = "Chỉnh sửa người dùng thành công!"
export const PASSWORD_OLD_ERR = "Sai mật khẩu, vui lòng thử lại!"
export const EDIT_CATEGORY_SUCCES = "Chỉnh sửa danh mục thành công!"
export const INVALID_CREDENTIALS = 'Thông tin không hợp lệ';
export const PASSWORD_FORMAT_ERROR = 'Mật khẩu không hợp lệ';
export const USERNAME_PASSWORD_ERROR = 'Sai tên đăng nhập và mật khẩu';
export const USERNAME_SPECIAL_CHAR_ERROR = 'Không được chứa ký tự đặc biệt';